CREATE TABLE [mir].[SsisLog]
(
	[Id] INT NOT NULL PRIMARY KEY
	, Event VARCHAR(255) NOT NULL
	, Computer VARCHAR(255) NOT NULL
	, Operator VARCHAR(255) NOT NULL
	, [Source] VARCHAR(255) NOT NULL
	, SourceId UNIQUEIDENTIFIER NOT NULL
	, ExecutionId UNIQUEIDENTIFIER NOT NULL
	, StartTime DATETIME NOT NULL
	, EndTime DATETIME NOT NULL
	, DataCode VARCHAR(20)
	,[Message] VARCHAR(max) NULL
)
